services:
  - type: web
    name: portfolio-hacker-chrisvd9
    env: node
    plan: free 
    branch: main
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    envVars:
      - key: NODE_ENV
        value: production

